#!bin/bash

readonly FILE_NAME="ex0"

number=$1

file=( "ft_ft.c" "ft_ultimate_ft.c" "ft_swap.c" "ft_div_mod.c" "ft_ultimate_div_mod.c" "ft_putstr.c" "ft_strlen.c" "ft_rev_int_tab.c" "ft_sort_int_tab.c")


for (( i=0; i <= $1 ; i++ ));
do
cd "$FILE_NAME$i"
echo "/////////////////////////// $FILE_NAME$i ////////////////////"
echo " "
echo "-------NORMINETTE------"
norminette ${file[i]}
echo "-----------------------"
echo "  "
echo "-------COMPILATION------"
gcc -Wall -Wextra -Werror main.c ${file[i]} && ./a.out | cat -e
echo "-----------------------"
echo " "
echo "-------CODE------"
cat -e ${file[i]}
echo "-----------------"
cd ..
done
echo "CREATE BY JREMY"
